{ ... }:
{
  imports = [
    ./autopairs.nix
    ./barbar.nix
    ./betterquickfix.nix
    ./blink.nix
    ./conform.nix
    ./dap.nix
    ./edgy.nix
    ./lazygit.nix
    ./lualine.nix
    ./lsp.nix
    ./noice.nix
    ./telescope.nix
    ./icons.nix
    ./instant.nix
    ./snacks.nix
    ./smear-cursor.nix
    ./surround.nix
    ./toggleterm.nix
    ./treesitter.nix
    ./treesitter-textobjects.nix
    ./trouble.nix
    ./typst-vim.nix
    ./vimtex.nix
    ./which-key.nix
    ./yanky.nix
    ./yazi.nix
  ];
}
