{ pkgs, config, ... }:

{
  # 1. Install Matugen and our bulletproof background script
  home.packages = with pkgs; [
    matugen
    (pkgs.writeShellScriptBin "update-theme" ''
      WP_PATH="$1"

      # If Noctalia didn't pass the path, extract it from the current state!
      if [ -z "$WP_PATH" ]; then
        WP_PATH=$(noctalia-shell ipc call state all | ${pkgs.jq}/bin/jq -r '.state.wallpapers | to_entries | .[0].value')
      fi

      if [ -z "$WP_PATH" ] || [ "$WP_PATH" = "null" ]; then
        echo "Error: Could not find wallpaper path."
        exit 1
      fi

      # Run Matugen, forcing the primary color selection to bypass the interactive prompt
      ${pkgs.matugen}/bin/matugen image "$WP_PATH" --source-color-index 0

      vicinae server --replace &
      sleep 1
      vicinae theme set matugen
    '')
  ];

  # 2. Feed Matugen the raw TOML template (Now with version = 1 and inherits)
  xdg.configFile."matugen/templates/vicinae.toml".text = ''
    [meta]
    version = 1
    name = "Matugen"
    description = "Material You theme generated by Matugen"
    variant = "dark"
    inherits = "vicinae-dark"

    [colors.core]
    accent = "{{colors.primary.default.hex}}"
    accent_foreground = "{{colors.on_primary.default.hex}}"
    background = "{{colors.surface.default.hex}}"
    foreground = "{{colors.on_surface.default.hex}}"
    secondary_background = "{{colors.surface_container.default.hex}}"
    border = "{{colors.outline_variant.default.hex}}"

    [colors.main_window]
    border = "{{colors.outline_variant.default.hex}}"

    [colors.settings_window]
    border = "{{colors.outline.default.hex}}"

    [colors.accents]
    blue = "{{colors.primary.default.hex}}"
    green = "{{colors.tertiary.default.hex}}"
    magenta = "{{colors.secondary.default.hex}}"
    red = "{{colors.error.default.hex}}"
    purple = "{{colors.secondary.default.hex}}"

    [colors.accents.orange]
    name = "{{colors.error.default.hex}}"
    lighter = 40

    [colors.accents.yellow]
    name = "{{colors.tertiary.default.hex}}"
    lighter = 80

    [colors.accents.cyan]
    name = "{{colors.primary.default.hex}}"
    lighter = 50

    [colors.text]
    default = "{{colors.on_surface.default.hex}}"
    muted = "{{colors.on_surface_variant.default.hex}}"
    danger = "{{colors.error.default.hex}}"
    success = "{{colors.tertiary.default.hex}}"

    [colors.text.placeholder]
    name = "{{colors.on_surface_variant.default.hex}}"
    opacity = 0.6

    [colors.text.selection]
    background = "{{colors.primary.default.hex}}"
    foreground = "{{colors.on_primary.default.hex}}"

    [colors.text.links]
    default = "{{colors.primary.default.hex}}"

    [colors.text.links.visited]
    name = "{{colors.tertiary.default.hex}}"
    darker = 20

    [colors.input]
    border = "{{colors.outline.default.hex}}"
    border_focus = "{{colors.primary.default.hex}}"
    border_error = "{{colors.error.default.hex}}"

    [colors.button.primary]
    background = "{{colors.surface_container_high.default.hex}}"
    foreground = "{{colors.on_surface.default.hex}}"

    [colors.button.primary.hover]
    background = "{{colors.surface_container_highest.default.hex}}"

    [colors.button.primary.focus]
    outline = "{{colors.primary.default.hex}}"

    [colors.list.item.hover]
    background = { name = "{{colors.primary_container.default.hex}}", opacity = 0.25 }
    foreground = "{{colors.on_surface.default.hex}}"

    [colors.list.item.selection]
    background = { name = "{{colors.primary_container.default.hex}}", opacity = 0.50 }
    foreground = "{{colors.on_primary_container.default.hex}}"
    secondary_background = "{{colors.primary_container.default.hex}}"
    secondary_foreground = "{{colors.on_primary_container.default.hex}}"

    [colors.grid.item]
    background = "{{colors.surface_container.default.hex}}"

    [colors.grid.item.hover.outline]
    name = "{{colors.secondary.default.hex}}"
    opacity = 0.8

    [colors.grid.item.selection.outline]
    name = "{{colors.primary.default.hex}}"

    [colors.scrollbars.background]
    name = "{{colors.primary.default.hex}}"
    opacity = 0.2

    [colors.loading]
    bar = "{{colors.primary.default.hex}}"
    spinner = "{{colors.primary.default.hex}}"
  '';

  # 3. Tell Matugen to route the output back to .config
  xdg.configFile."matugen/config.toml".text = ''
    [config.wallpaper]
    command = "echo" 
    set = false      

    [templates.vicinae]
    input_path = "${config.xdg.configHome}/matugen/templates/vicinae.toml"
    output_path = "${config.xdg.dataHome}/vicinae/themes/matugen.toml"
  '';

  # Force Home Manager to create the correct themes directory
  home.file.".local/share/vicinae/themes/.keep".text = "";
}
