{
  pkgs,
  lib,
  config,
  inputs,
  ...
}:

let
  # The reload hook handles live updates after Noctalia writes the new files
  reloadHook = pkgs.writeShellScriptBin "noctalia-reload-hook" ''
    # Apply the newly generated Lua config to the live session
    hyprctl eval "$(cat ${config.xdg.configHome}/hypr/colors.lua)"

    # Restart vicinae server so it gets the latest theme
    vicinae server --replace &
    sleep 1
    vicinae theme set matugen
  '';
in
{
  imports = [
    inputs.noctalia.homeModules.default
  ];

  programs.noctalia = {
    enable = true;

    settings = {
      bar = {
        main = {
          position = "top";
          capsule = "true";
        };
      };

      control_center = {
        width = 1200;
      };

      weather = {
        enabled = true;
        refresh_minutes = 15;
        unit = "metric";
        effects = true;
      };

      location = {
        auto_locate = true;
      };

      wallpaper = {
        enabled = true;
        directory = "/home/iris/dotfiles/Wallpapers";
      };
    };
  };

  # --- Noctalia Wallpaper Color Switching ---

  xdg.configFile."noctalia/templates/vicinae.toml".text = ''
    [meta]
    version = 1
    name = "Matugen"
    description = "Material You theme generated by Matugen"
    variant = "dark"
    inherits = "vicinae-dark"

    [colors.core]
    accent = "{{colors.primary.default.hex}}"
    accent_foreground = "{{colors.on_primary.default.hex}}"
    background = "{{colors.surface.default.hex}}"
    foreground = "{{colors.on_surface.default.hex}}"
    secondary_background = "{{colors.surface_container.default.hex}}"
    border = "{{colors.outline_variant.default.hex}}"

    [colors.main_window]
    border = "{{colors.outline_variant.default.hex}}"

    [colors.settings_window]
    border = "{{colors.outline.default.hex}}"

    [colors.accents]
    blue = "{{colors.primary.default.hex}}"
    green = "{{colors.tertiary.default.hex}}"
    magenta = "{{colors.secondary.default.hex}}"
    red = "{{colors.error.default.hex}}"
    purple = "{{colors.secondary.default.hex}}"

    [colors.accents.orange]
    name = "{{colors.error.default.hex}}"
    lighter = 40

    [colors.accents.yellow]
    name = "{{colors.tertiary.default.hex}}"
    lighter = 80

    [colors.accents.cyan]
    name = "{{colors.primary.default.hex}}"
    lighter = 50

    [colors.text]
    default = "{{colors.on_surface.default.hex}}"
    muted = "{{colors.on_surface_variant.default.hex}}"
    danger = "{{colors.error.default.hex}}"
    success = "{{colors.tertiary.default.hex}}"

    [colors.text.placeholder]
    name = "{{colors.on_surface_variant.default.hex}}"
    opacity = 0.6

    [colors.text.selection]
    background = "{{colors.primary.default.hex}}"
    foreground = "{{colors.on_primary.default.hex}}"

    [colors.text.links]
    default = "{{colors.primary.default.hex}}"

    [colors.text.links.visited]
    name = "{{colors.tertiary.default.hex}}"
    darker = 20

    [colors.input]
    border = "{{colors.outline.default.hex}}"
    border_focus = "{{colors.primary.default.hex}}"
    border_error = "{{colors.error.default.hex}}"

    [colors.button.primary]
    background = "{{colors.surface_container_high.default.hex}}"
    foreground = "{{colors.on_surface.default.hex}}"

    [colors.button.primary.hover]
    background = "{{colors.surface_container_highest.default.hex}}"

    [colors.button.primary.focus]
    outline = "{{colors.primary.default.hex}}"

    [colors.list.item.hover]
    background = { name = "{{colors.primary_container.default.hex}}", opacity = 0.25 }
    foreground = "{{colors.on_surface.default.hex}}"

    [colors.list.item.selection]
    background = { name = "{{colors.primary_container.default.hex}}", opacity = 0.50 }
    foreground = "{{colors.on_primary_container.default.hex}}"
    secondary_background = "{{colors.primary_container.default.hex}}"
    secondary_foreground = "{{colors.on_primary_container.default.hex}}"

    [colors.grid.item]
    background = "{{colors.surface_container.default.hex}}"

    [colors.grid.item.hover.outline]
    name = "{{colors.secondary.default.hex}}"
    opacity = 0.8

    [colors.grid.item.selection.outline]
    name = "{{colors.primary.default.hex}}"

    [colors.scrollbars.background]
    name = "{{colors.primary.default.hex}}"
    opacity = 0.2

    [colors.loading]
    bar = "{{colors.primary.default.hex}}"
    spinner = "{{colors.primary.default.hex}}"
  '';

  xdg.configFile."noctalia/templates/colors.lua".text = ''
    hl.config({ 
      general = { 
        ["col.active_border"] = { 
          colors = { "rgb({{colors.primary.default.hex_stripped}})", "rgb({{colors.primary.default.hex_stripped}})" }, 
          angle = 45 
        } 
      } 
    })
  '';

  xdg.configFile."noctalia/user-templates.toml".text = ''
    [vicinae]
    input_path = "${config.xdg.configHome}/noctalia/templates/vicinae.toml"
    output_path = "${config.xdg.dataHome}/vicinae/themes/matugen.toml"
    command = "${lib.getExe reloadHook}"

    [hyprland_colors]
    input_path = "${config.xdg.configHome}/noctalia/templates/colors.lua"
    output_path = "${config.xdg.configHome}/hypr/colors.lua"
  '';

  home.activation.hyprlandColors = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    if [ ! -f "${config.xdg.configHome}/hypr/colors.lua" ]; then
      echo 'hl.config({ general = { ["col.active_border"] = { colors = { "rgb(ffffff)", "rgb(ffffff)" }, angle = 45 } } })' \
        > "${config.xdg.configHome}/hypr/colors.lua"
    fi
  '';

  home.file.".local/share/vicinae/themes/.keep".text = "";
}
